package com.smart.model;

import java.util.Date;

public class Clue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.id
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.status
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.name
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.tel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.companyName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.companyTel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String companyTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.companyPersonName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String companyPersonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.companyPersonTel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String companyPersonTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.companyPersonSex
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String companyPersonSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.companyPersonEmail
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String companyPersonEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.companyAddress
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.jobTitle
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String jobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.createTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.lastUpdateTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.assignTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private Date assignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.clueSource
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String clueSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.activityName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.department
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.person
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.remark
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.id
     *
     * @return the value of clue.id
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.id
     *
     * @param id the value for clue.id
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.status
     *
     * @return the value of clue.status
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.status
     *
     * @param status the value for clue.status
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.name
     *
     * @return the value of clue.name
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.name
     *
     * @param name the value for clue.name
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.tel
     *
     * @return the value of clue.tel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.tel
     *
     * @param tel the value for clue.tel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.companyName
     *
     * @return the value of clue.companyName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.companyName
     *
     * @param companyName the value for clue.companyName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.companyTel
     *
     * @return the value of clue.companyTel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.companyTel
     *
     * @param companyTel the value for clue.companyTel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.companyPersonName
     *
     * @return the value of clue.companyPersonName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getCompanyPersonName() {
        return companyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.companyPersonName
     *
     * @param companyPersonName the value for clue.companyPersonName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setCompanyPersonName(String companyPersonName) {
        this.companyPersonName = companyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.companyPersonTel
     *
     * @return the value of clue.companyPersonTel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getCompanyPersonTel() {
        return companyPersonTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.companyPersonTel
     *
     * @param companyPersonTel the value for clue.companyPersonTel
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setCompanyPersonTel(String companyPersonTel) {
        this.companyPersonTel = companyPersonTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.companyPersonSex
     *
     * @return the value of clue.companyPersonSex
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getCompanyPersonSex() {
        return companyPersonSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.companyPersonSex
     *
     * @param companyPersonSex the value for clue.companyPersonSex
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setCompanyPersonSex(String companyPersonSex) {
        this.companyPersonSex = companyPersonSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.companyPersonEmail
     *
     * @return the value of clue.companyPersonEmail
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getCompanyPersonEmail() {
        return companyPersonEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.companyPersonEmail
     *
     * @param companyPersonEmail the value for clue.companyPersonEmail
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setCompanyPersonEmail(String companyPersonEmail) {
        this.companyPersonEmail = companyPersonEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.companyAddress
     *
     * @return the value of clue.companyAddress
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.companyAddress
     *
     * @param companyAddress the value for clue.companyAddress
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.jobTitle
     *
     * @return the value of clue.jobTitle
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.jobTitle
     *
     * @param jobTitle the value for clue.jobTitle
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.createTime
     *
     * @return the value of clue.createTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.createTime
     *
     * @param createTime the value for clue.createTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.lastUpdateTime
     *
     * @return the value of clue.lastUpdateTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.lastUpdateTime
     *
     * @param lastUpdateTime the value for clue.lastUpdateTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.assignTime
     *
     * @return the value of clue.assignTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public Date getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.assignTime
     *
     * @param assignTime the value for clue.assignTime
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setAssignTime(Date assignTime) {
        this.assignTime = assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.clueSource
     *
     * @return the value of clue.clueSource
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getClueSource() {
        return clueSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.clueSource
     *
     * @param clueSource the value for clue.clueSource
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setClueSource(String clueSource) {
        this.clueSource = clueSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.activityName
     *
     * @return the value of clue.activityName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.activityName
     *
     * @param activityName the value for clue.activityName
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.department
     *
     * @return the value of clue.department
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.department
     *
     * @param department the value for clue.department
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.person
     *
     * @return the value of clue.person
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.person
     *
     * @param person the value for clue.person
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setPerson(String person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.remark
     *
     * @return the value of clue.remark
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.remark
     *
     * @param remark the value for clue.remark
     *
     * @mbg.generated Sat Jun 08 14:47:59 CST 2024
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}