package com.smart.crm.clue;

import java.util.Date;

public class Activities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.activity_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.department
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.user_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.status
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.start_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.end_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.is_delete
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.create_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.activity_content
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String activityContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.id
     *
     * @return the value of activities.id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.id
     *
     * @param id the value for activities.id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.activity_name
     *
     * @return the value of activities.activity_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.activity_name
     *
     * @param activityName the value for activities.activity_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.department
     *
     * @return the value of activities.department
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.department
     *
     * @param department the value for activities.department
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.user_id
     *
     * @return the value of activities.user_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.user_id
     *
     * @param userId the value for activities.user_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.status
     *
     * @return the value of activities.status
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.status
     *
     * @param status the value for activities.status
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.start_time
     *
     * @return the value of activities.start_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.start_time
     *
     * @param startTime the value for activities.start_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.end_time
     *
     * @return the value of activities.end_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.end_time
     *
     * @param endTime the value for activities.end_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.is_delete
     *
     * @return the value of activities.is_delete
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.is_delete
     *
     * @param isDelete the value for activities.is_delete
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.create_time
     *
     * @return the value of activities.create_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.create_time
     *
     * @param createTime the value for activities.create_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.activity_content
     *
     * @return the value of activities.activity_content
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.activity_content
     *
     * @param activityContent the value for activities.activity_content
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }
}