package com.smart.crm.clue;

import java.util.Date;

public class Clue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.status
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.company_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.company_tel
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String companyTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.company_contacts_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String companyContactsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.company_contacts_tel
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String companyContactsTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.company_contacts_sex
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Integer companyContactsSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.company_contacts_email
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String companyContactsEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.company_address
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.company_contacts_job_title
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String companyContactsJobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.create_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.update_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.assign_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private Date assignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.clue_source
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String clueSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.activity_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.user_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue.remark
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.id
     *
     * @return the value of clue.id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.id
     *
     * @param id the value for clue.id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.status
     *
     * @return the value of clue.status
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.status
     *
     * @param status the value for clue.status
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.company_name
     *
     * @return the value of clue.company_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.company_name
     *
     * @param companyName the value for clue.company_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.company_tel
     *
     * @return the value of clue.company_tel
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.company_tel
     *
     * @param companyTel the value for clue.company_tel
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel == null ? null : companyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.company_contacts_name
     *
     * @return the value of clue.company_contacts_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getCompanyContactsName() {
        return companyContactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.company_contacts_name
     *
     * @param companyContactsName the value for clue.company_contacts_name
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCompanyContactsName(String companyContactsName) {
        this.companyContactsName = companyContactsName == null ? null : companyContactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.company_contacts_tel
     *
     * @return the value of clue.company_contacts_tel
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getCompanyContactsTel() {
        return companyContactsTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.company_contacts_tel
     *
     * @param companyContactsTel the value for clue.company_contacts_tel
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCompanyContactsTel(String companyContactsTel) {
        this.companyContactsTel = companyContactsTel == null ? null : companyContactsTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.company_contacts_sex
     *
     * @return the value of clue.company_contacts_sex
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Integer getCompanyContactsSex() {
        return companyContactsSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.company_contacts_sex
     *
     * @param companyContactsSex the value for clue.company_contacts_sex
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCompanyContactsSex(Integer companyContactsSex) {
        this.companyContactsSex = companyContactsSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.company_contacts_email
     *
     * @return the value of clue.company_contacts_email
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getCompanyContactsEmail() {
        return companyContactsEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.company_contacts_email
     *
     * @param companyContactsEmail the value for clue.company_contacts_email
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCompanyContactsEmail(String companyContactsEmail) {
        this.companyContactsEmail = companyContactsEmail == null ? null : companyContactsEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.company_address
     *
     * @return the value of clue.company_address
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.company_address
     *
     * @param companyAddress the value for clue.company_address
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.company_contacts_job_title
     *
     * @return the value of clue.company_contacts_job_title
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getCompanyContactsJobTitle() {
        return companyContactsJobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.company_contacts_job_title
     *
     * @param companyContactsJobTitle the value for clue.company_contacts_job_title
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCompanyContactsJobTitle(String companyContactsJobTitle) {
        this.companyContactsJobTitle = companyContactsJobTitle == null ? null : companyContactsJobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.create_time
     *
     * @return the value of clue.create_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.create_time
     *
     * @param createTime the value for clue.create_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.update_time
     *
     * @return the value of clue.update_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.update_time
     *
     * @param updateTime the value for clue.update_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.assign_time
     *
     * @return the value of clue.assign_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Date getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.assign_time
     *
     * @param assignTime the value for clue.assign_time
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setAssignTime(Date assignTime) {
        this.assignTime = assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.clue_source
     *
     * @return the value of clue.clue_source
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getClueSource() {
        return clueSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.clue_source
     *
     * @param clueSource the value for clue.clue_source
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setClueSource(String clueSource) {
        this.clueSource = clueSource == null ? null : clueSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.activity_id
     *
     * @return the value of clue.activity_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.activity_id
     *
     * @param activityId the value for clue.activity_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.user_id
     *
     * @return the value of clue.user_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.user_id
     *
     * @param userId the value for clue.user_id
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue.remark
     *
     * @return the value of clue.remark
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue.remark
     *
     * @param remark the value for clue.remark
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}