package com.smart.crm.clue;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public ClueExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIsNull() {
            addCriterion("company_tel is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIsNotNull() {
            addCriterion("company_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTelEqualTo(String value) {
            addCriterion("company_tel =", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotEqualTo(String value) {
            addCriterion("company_tel <>", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelGreaterThan(String value) {
            addCriterion("company_tel >", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelGreaterThanOrEqualTo(String value) {
            addCriterion("company_tel >=", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLessThan(String value) {
            addCriterion("company_tel <", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLessThanOrEqualTo(String value) {
            addCriterion("company_tel <=", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLike(String value) {
            addCriterion("company_tel like", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotLike(String value) {
            addCriterion("company_tel not like", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIn(List<String> values) {
            addCriterion("company_tel in", values, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotIn(List<String> values) {
            addCriterion("company_tel not in", values, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelBetween(String value1, String value2) {
            addCriterion("company_tel between", value1, value2, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotBetween(String value1, String value2) {
            addCriterion("company_tel not between", value1, value2, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameIsNull() {
            addCriterion("company_contacts_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameIsNotNull() {
            addCriterion("company_contacts_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameEqualTo(String value) {
            addCriterion("company_contacts_name =", value, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameNotEqualTo(String value) {
            addCriterion("company_contacts_name <>", value, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameGreaterThan(String value) {
            addCriterion("company_contacts_name >", value, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_contacts_name >=", value, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameLessThan(String value) {
            addCriterion("company_contacts_name <", value, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameLessThanOrEqualTo(String value) {
            addCriterion("company_contacts_name <=", value, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameLike(String value) {
            addCriterion("company_contacts_name like", value, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameNotLike(String value) {
            addCriterion("company_contacts_name not like", value, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameIn(List<String> values) {
            addCriterion("company_contacts_name in", values, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameNotIn(List<String> values) {
            addCriterion("company_contacts_name not in", values, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameBetween(String value1, String value2) {
            addCriterion("company_contacts_name between", value1, value2, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsNameNotBetween(String value1, String value2) {
            addCriterion("company_contacts_name not between", value1, value2, "companyContactsName");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelIsNull() {
            addCriterion("company_contacts_tel is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelIsNotNull() {
            addCriterion("company_contacts_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelEqualTo(String value) {
            addCriterion("company_contacts_tel =", value, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelNotEqualTo(String value) {
            addCriterion("company_contacts_tel <>", value, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelGreaterThan(String value) {
            addCriterion("company_contacts_tel >", value, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelGreaterThanOrEqualTo(String value) {
            addCriterion("company_contacts_tel >=", value, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelLessThan(String value) {
            addCriterion("company_contacts_tel <", value, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelLessThanOrEqualTo(String value) {
            addCriterion("company_contacts_tel <=", value, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelLike(String value) {
            addCriterion("company_contacts_tel like", value, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelNotLike(String value) {
            addCriterion("company_contacts_tel not like", value, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelIn(List<String> values) {
            addCriterion("company_contacts_tel in", values, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelNotIn(List<String> values) {
            addCriterion("company_contacts_tel not in", values, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelBetween(String value1, String value2) {
            addCriterion("company_contacts_tel between", value1, value2, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsTelNotBetween(String value1, String value2) {
            addCriterion("company_contacts_tel not between", value1, value2, "companyContactsTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexIsNull() {
            addCriterion("company_contacts_sex is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexIsNotNull() {
            addCriterion("company_contacts_sex is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexEqualTo(Integer value) {
            addCriterion("company_contacts_sex =", value, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexNotEqualTo(Integer value) {
            addCriterion("company_contacts_sex <>", value, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexGreaterThan(Integer value) {
            addCriterion("company_contacts_sex >", value, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_contacts_sex >=", value, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexLessThan(Integer value) {
            addCriterion("company_contacts_sex <", value, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexLessThanOrEqualTo(Integer value) {
            addCriterion("company_contacts_sex <=", value, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexIn(List<Integer> values) {
            addCriterion("company_contacts_sex in", values, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexNotIn(List<Integer> values) {
            addCriterion("company_contacts_sex not in", values, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexBetween(Integer value1, Integer value2) {
            addCriterion("company_contacts_sex between", value1, value2, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsSexNotBetween(Integer value1, Integer value2) {
            addCriterion("company_contacts_sex not between", value1, value2, "companyContactsSex");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailIsNull() {
            addCriterion("company_contacts_email is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailIsNotNull() {
            addCriterion("company_contacts_email is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailEqualTo(String value) {
            addCriterion("company_contacts_email =", value, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailNotEqualTo(String value) {
            addCriterion("company_contacts_email <>", value, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailGreaterThan(String value) {
            addCriterion("company_contacts_email >", value, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailGreaterThanOrEqualTo(String value) {
            addCriterion("company_contacts_email >=", value, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailLessThan(String value) {
            addCriterion("company_contacts_email <", value, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailLessThanOrEqualTo(String value) {
            addCriterion("company_contacts_email <=", value, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailLike(String value) {
            addCriterion("company_contacts_email like", value, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailNotLike(String value) {
            addCriterion("company_contacts_email not like", value, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailIn(List<String> values) {
            addCriterion("company_contacts_email in", values, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailNotIn(List<String> values) {
            addCriterion("company_contacts_email not in", values, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailBetween(String value1, String value2) {
            addCriterion("company_contacts_email between", value1, value2, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsEmailNotBetween(String value1, String value2) {
            addCriterion("company_contacts_email not between", value1, value2, "companyContactsEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNull() {
            addCriterion("company_address is null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNotNull() {
            addCriterion("company_address is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressEqualTo(String value) {
            addCriterion("company_address =", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotEqualTo(String value) {
            addCriterion("company_address <>", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThan(String value) {
            addCriterion("company_address >", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("company_address >=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThan(String value) {
            addCriterion("company_address <", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThanOrEqualTo(String value) {
            addCriterion("company_address <=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLike(String value) {
            addCriterion("company_address like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotLike(String value) {
            addCriterion("company_address not like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIn(List<String> values) {
            addCriterion("company_address in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotIn(List<String> values) {
            addCriterion("company_address not in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressBetween(String value1, String value2) {
            addCriterion("company_address between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotBetween(String value1, String value2) {
            addCriterion("company_address not between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleIsNull() {
            addCriterion("company_contacts_job_title is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleIsNotNull() {
            addCriterion("company_contacts_job_title is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleEqualTo(String value) {
            addCriterion("company_contacts_job_title =", value, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleNotEqualTo(String value) {
            addCriterion("company_contacts_job_title <>", value, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleGreaterThan(String value) {
            addCriterion("company_contacts_job_title >", value, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleGreaterThanOrEqualTo(String value) {
            addCriterion("company_contacts_job_title >=", value, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleLessThan(String value) {
            addCriterion("company_contacts_job_title <", value, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleLessThanOrEqualTo(String value) {
            addCriterion("company_contacts_job_title <=", value, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleLike(String value) {
            addCriterion("company_contacts_job_title like", value, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleNotLike(String value) {
            addCriterion("company_contacts_job_title not like", value, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleIn(List<String> values) {
            addCriterion("company_contacts_job_title in", values, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleNotIn(List<String> values) {
            addCriterion("company_contacts_job_title not in", values, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleBetween(String value1, String value2) {
            addCriterion("company_contacts_job_title between", value1, value2, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCompanyContactsJobTitleNotBetween(String value1, String value2) {
            addCriterion("company_contacts_job_title not between", value1, value2, "companyContactsJobTitle");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeIsNull() {
            addCriterion("assign_time is null");
            return (Criteria) this;
        }

        public Criteria andAssignTimeIsNotNull() {
            addCriterion("assign_time is not null");
            return (Criteria) this;
        }

        public Criteria andAssignTimeEqualTo(Date value) {
            addCriterion("assign_time =", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeNotEqualTo(Date value) {
            addCriterion("assign_time <>", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeGreaterThan(Date value) {
            addCriterion("assign_time >", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("assign_time >=", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeLessThan(Date value) {
            addCriterion("assign_time <", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeLessThanOrEqualTo(Date value) {
            addCriterion("assign_time <=", value, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeIn(List<Date> values) {
            addCriterion("assign_time in", values, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeNotIn(List<Date> values) {
            addCriterion("assign_time not in", values, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeBetween(Date value1, Date value2) {
            addCriterion("assign_time between", value1, value2, "assignTime");
            return (Criteria) this;
        }

        public Criteria andAssignTimeNotBetween(Date value1, Date value2) {
            addCriterion("assign_time not between", value1, value2, "assignTime");
            return (Criteria) this;
        }

        public Criteria andClueSourceIsNull() {
            addCriterion("clue_source is null");
            return (Criteria) this;
        }

        public Criteria andClueSourceIsNotNull() {
            addCriterion("clue_source is not null");
            return (Criteria) this;
        }

        public Criteria andClueSourceEqualTo(String value) {
            addCriterion("clue_source =", value, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceNotEqualTo(String value) {
            addCriterion("clue_source <>", value, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceGreaterThan(String value) {
            addCriterion("clue_source >", value, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceGreaterThanOrEqualTo(String value) {
            addCriterion("clue_source >=", value, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceLessThan(String value) {
            addCriterion("clue_source <", value, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceLessThanOrEqualTo(String value) {
            addCriterion("clue_source <=", value, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceLike(String value) {
            addCriterion("clue_source like", value, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceNotLike(String value) {
            addCriterion("clue_source not like", value, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceIn(List<String> values) {
            addCriterion("clue_source in", values, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceNotIn(List<String> values) {
            addCriterion("clue_source not in", values, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceBetween(String value1, String value2) {
            addCriterion("clue_source between", value1, value2, "clueSource");
            return (Criteria) this;
        }

        public Criteria andClueSourceNotBetween(String value1, String value2) {
            addCriterion("clue_source not between", value1, value2, "clueSource");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNull() {
            addCriterion("activity_id is null");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNotNull() {
            addCriterion("activity_id is not null");
            return (Criteria) this;
        }

        public Criteria andActivityIdEqualTo(String value) {
            addCriterion("activity_id =", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotEqualTo(String value) {
            addCriterion("activity_id <>", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThan(String value) {
            addCriterion("activity_id >", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThanOrEqualTo(String value) {
            addCriterion("activity_id >=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThan(String value) {
            addCriterion("activity_id <", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThanOrEqualTo(String value) {
            addCriterion("activity_id <=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLike(String value) {
            addCriterion("activity_id like", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotLike(String value) {
            addCriterion("activity_id not like", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIn(List<String> values) {
            addCriterion("activity_id in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotIn(List<String> values) {
            addCriterion("activity_id not in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdBetween(String value1, String value2) {
            addCriterion("activity_id between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotBetween(String value1, String value2) {
            addCriterion("activity_id not between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clue
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 15 16:31:43 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clue
     *
     * @mbg.generated Sat Jun 15 16:31:43 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}